### ISSUE TITLE
Error with SyliusAdminBundleCrud

### ISSUE THREAD

**Issue by Nana-asiamah98** [odiseoteam/SyliusAvataxPlugin#2]
Hello Odiseoteam.

Has the `templates: SyliusAdminBundle:Crud` been updated to` templates: "@SyliusAdmin\\Crud"`? I always face the same error with the SyliusAdminBundle anytime I run a composer update or install.

**Comment by bigboss86** [comment]
Sorry @Nana-asiamah98, I forgot to tag the fix.
Now it's done. Thanks!

**Comment by Nana-asiamah98** [comment]
You're welcome.
